### ISSUE TITLE
Error when running sd-3.5-medium, but sd-3.5-large could run.

### ISSUE THREAD

**Issue by Hatter77** [BlueDyee/TF-TI2I#2]
When I run code with sd-3.5-medium, I get the following error:

    File "/home/u2023030056/network/TF-TI2I-main/src/attn_processor.py", line 2041, in __call__
        hidden_states[bs:bs+1] = main_hidden_states
    UnboundLocalError: local variable 'main_hidden_states' referenced before assignment

However, running the same code with sd-3.5-large works fine.

I would appreciate any guidance on how to resolve this issue.

**Comment by BlueDyee** [comment]
It seems that the number of layers differs between 3.5-medium and 3.5-large,
which causes a mismatch error in the AttnProcessor.
In TF-TI2I.ipynb
You could see this block
```
    for child in net.children():
        if "Attention" in child.__class__.__name__:
            child.processor = TI2I_JointAttnProcessor2_0_multi(layer=layer_count, contextual_replace=True,
                                                            wta_control_signal={"on":True,
                                                                                "hyper_parameter":{
                                                                                                "wta_weight":[1, 1, 1,1],
                                                                                                "cross2ref":True,
                                                                                                "wta_shift":[0, 0, 0,0],
                                                                                                "wta_cross":False
                                                                                                },
                                                                                "debug":False},
                                                            ref_control_signal={"on":True,
                                                                                "ref_idxs":[0,1,2,3], 
                                                                                "control_type":"main_context",
                                                                                "debug":False,
                                                                                "control_layers":[i for i in range(25,40)],
                                                                                "hyper_parameter":{}},
                                                                                )
            attn_processors.append(child.processor)
            layer_count += 1
        iter_net(child)
iter_net(pipe.transformer)
```
You can try lowering the range of control_layers to match your model’s layer depth.
For example, change:
```
"control_layers": [i for i in range(25, 40)],
```
to something like:
```
"control_layers": [i for i in range(0, 10)],
```
This should fix the issue.

**Comment by Hatter77** [comment]
Thank you for your suggestion. I tried it, but unfortunately, it still doesn't work after changing the range of control_layers.

**Comment by BlueDyee** [comment]
Could you check if you modified the "TF-TI2I-main/src/attn_processor.py"?
I just use the original code as below, and everything go smoothly

```
import PIL
from diffusers.utils import make_image_grid
import torch
from diffusers import StableDiffusion3Pipeline
from src.customized_pipe import TI2I_StableDiffusion3Pipeline
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
pipe = TI2I_StableDiffusion3Pipeline.from_pretrained("stabilityai/stable-diffusion-3-medium-diffusers", torch_dtype=torch.float16).to("cuda")
```

```
from src.attn_processor import TI2I_JointAttnProcessor2_0_multi
obj_prompt = "a dinosaur"
tex_prompt = "crystal"
act_prompt = "breathing fire"
bg_prompt = "Starry Night"

main_prompt=f"{obj_prompt} with texture of {tex_prompt} doing {act_prompt} in {bg_prompt}"
sub_prompts=[obj_prompt, tex_prompt, act_prompt,bg_prompt]
refer_images=[PIL.Image.open("refer_data/A dinosaur.png").resize((1024,1024)),
              PIL.Image.open("refer_data/crystal dog.png").resize((1024,1024)),
              PIL.Image.open("refer_data/breathing fire.png").resize((1024,1024)),
              PIL.Image.open("refer_data/ood_starry.jpg").resize((1024,1024)),
              ]


layer_count = 0
attn_processors = []
def iter_net(net):
    global layer_count
    for child in net.children():
        if "Attention" in child.__class__.__name__:
            child.processor = TI2I_JointAttnProcessor2_0_multi(layer=layer_count, contextual_replace=True,
                                                            wta_control_signal={"on":True,
                                                                                "hyper_parameter":{
                                                                                                "wta_weight":[1, 1, 1,1],
                                                                                                "cross2ref":True,
                                                                                                "wta_shift":[0, 0, 0,0],
                                                                                                "wta_cross":False
                                                                                                },
                                                                                "debug":False},
                                                            ref_control_signal={"on":True,
                                                                                "ref_idxs":[0,1,2,3], 
                                                                                "control_type":"main_context",
                                                                                "debug":False,
                                                                                "control_layers":[i for i in range(25,40)],
                                                                                "hyper_parameter":{}},
                                                                                )
            attn_processors.append(child.processor)
            layer_count += 1
        iter_net(child)

iter_net(pipe.transformer)

torch.manual_seed(0)
pipe.enable_attention_slicing()

switch_images = pipe.img2img_multi(
images=refer_images,
prompt_a=main_prompt,
prompt_b=sub_prompts,
negative_prompt="",
num_inference_steps=28,
guidance_scale=5,
strength=1,
height=1024,
width=1024,
)
make_image_grid(switch_images, rows=1, cols=len(switch_images))
```

<img width="1274" height="292" alt="Image" src="https://github.com/user-attachments/assets/0d7aed97-e58d-42cb-ac77-0bea8317a0a7" />

**Comment by Hatter77** [comment]
I figured out the problem. 
It errors out with stable-diffusion-3.5-medium but works fine with stable-diffusion-3-medium-diffusers. 
Thanks for your help ^_^ .

**Comment by BlueDyee** [comment]
Glad to hear you fixed the bug!
